services:
  # Database service
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  # Backend vue service
  backend:
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./backend
    environment:
      - PORT=${BACKEND_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend Vue service
  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ./frontend
    environment:
      - API_URI=http://localhost:${BACKEND_PORT}/studium/v1/api
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
  backend:
  frontend:
